services:
  web:
    image: nginx:latest
    container_name: web
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8088:80
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    env_file:
      - .env
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.4.0
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome-debug:latest
    container_name: selenium
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - app-network

  php_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_test
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - selenium
      - php
    environment:
      APP_ENV: testing
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: adota_parana
      DB_USERNAME: root
      DB_PASSWORD: rootpwd

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
