    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>Editar Informações de <?= htmlspecialchars($pet->name) ?></h2>
                <hr>
                <form action="/pets/<?= $pet->id ?>/update" method="POST" enctype="multipart/form-data">
                    <?php include '_form.phtml'; ?>
                </form>
            </div>
        </div>
    </div>